"""empty message

Revision ID: 3f7469fd0b40
Revises: afc66c704353
Create Date: 2023-01-26 20:16:32.930691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7469fd0b40'
down_revision = 'afc66c704353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.String(length=250), nullable=True),
    sa.Column('rotation_period', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    op.drop_table('planet')
    # ### end Alembic commands ###
